$(document).ready(function(){
    $("#a1").click(function(){
        $("#item1").text("人興財旺富貴長");
        $("#item2").text("龍行大運");
        $("#item4").text("龍騰虎躍家興旺");
    });
    $("#a2").click(function(){
        $("#item1").text("龍騰盛世領春來");
        $("#item2").text("前程似錦");
        $("#item4").text("兔搭神舟登月去");
    });
    $("#a3").click(function(){
        $("#item1").text("飛天彩鳳舞新春");
        $("#item2").text("一帆風順");
        $("#item4").text("出海金龍吟盛世");
    });
});
